// Loop — brand definitions for 4 switchable demo restaurants
// Each brand is a full theme: colors, type, voice, reward, hero

const BRANDS = {
  filter: {
    id: 'filter',
    name: 'Filter & Co',
    tagline: 'Specialty coffee · Indiranagar',
    type: 'High frequency · daily/weekly',
    bg: '#F4EFE5',
    surface: '#FFFDF7',
    ink: '#1A2622',
    inkSoft: '#4A5A53',
    mute: '#8B9990',
    line: '#D9D0BD',
    accent: '#0F4C3A',       // deep forest
    accentSoft: '#DEEBE3',
    accentInk: '#0F4C3A',
    contrast: '#E54B1C',
    fontDisplay: '"Instrument Serif", serif',
    fontUi: '"Geist", sans-serif',
    rewardName: 'Free cold brew',
    rewardEmoji: '☕',
    loopTotal: 5,
    progress: 3,
    hero: 'linear-gradient(135deg, #2A1F1A 0%, #0F1F1A 100%)',
    welcome: 'Welcome to Filter & Co',
    promise: 'Get a free cold brew after 5 visits',
    coupon: 'BREW-8K4',
    voice: 'warm, precise',
    activity: { title: 'Leave a Google review', reward: 'free pastry today' },
  },
  sunday: {
    id: 'sunday',
    name: 'Sunday Social',
    tagline: 'All-day brunch · Koramangala',
    type: 'Mid frequency · weekly/monthly',
    bg: '#FAEFE3',
    surface: '#FFF8EE',
    ink: '#2A1810',
    inkSoft: '#5A382A',
    mute: '#9A7864',
    line: '#E8D4BE',
    accent: '#C2563B',       // terracotta
    accentSoft: '#F9DCCB',
    accentInk: '#8E3A22',
    contrast: '#175F45',
    fontDisplay: '"Instrument Serif", serif',
    fontUi: '"Geist", sans-serif',
    rewardName: 'Free starter on us',
    rewardEmoji: '𓍙',
    loopTotal: 5,
    progress: 2,
    hero: 'linear-gradient(150deg, #C2563B 0%, #8E3A22 100%)',
    welcome: 'Hey, welcome in.',
    promise: 'Brunch with us 5 times — get a starter on the house',
    coupon: 'BRNCH-2X1',
    voice: 'friendly, easy',
    activity: { title: 'Share a story tagging us', reward: '20% off next visit' },
  },
  bombay: {
    id: 'bombay',
    name: 'Bombay Local',
    tagline: 'Brewpub · HSR Layout',
    type: 'Social-heavy · weekend',
    bg: '#1A1A1A',
    surface: '#0F0F0F',
    ink: '#F4E8C8',
    inkSoft: '#C8BC9E',
    mute: '#7A7264',
    line: '#3A3528',
    accent: '#FFD028',       // electric yellow
    accentSoft: '#3A3010',
    accentInk: '#FFD028',
    contrast: '#FF5A3A',
    fontDisplay: '"Instrument Serif", serif',
    fontUi: '"Geist", sans-serif',
    rewardName: 'Round on the house',
    rewardEmoji: '𖠰',
    loopTotal: 6,
    progress: 4,
    hero: 'linear-gradient(180deg, #1A1A1A 0%, #050505 100%)',
    welcome: 'You\'re in.',
    promise: 'Six visits. One round of beers on us.',
    coupon: 'BREW-FT2',
    voice: 'bold, direct',
    activity: { title: 'Post a reel with our tag', reward: 'private tasting invite' },
    dark: true,
  },
  atelier: {
    id: 'atelier',
    name: 'Atelier 14',
    tagline: 'Tasting menu · Lavelle Road',
    type: 'Low frequency · high value',
    bg: '#F1ECE3',
    surface: '#FAF6EB',
    ink: '#221C1A',
    inkSoft: '#4A3E3A',
    mute: '#8C7E78',
    line: '#D8CCB8',
    accent: '#6B1F2F',       // deep burgundy
    accentSoft: '#EFD8DC',
    accentInk: '#6B1F2F',
    contrast: '#C58B14',
    fontDisplay: '"Instrument Serif", serif',
    fontUi: '"Geist", sans-serif',
    rewardName: 'Chef\'s amuse-bouche',
    rewardEmoji: '★',
    loopTotal: 3,
    progress: 2,
    hero: 'linear-gradient(160deg, #2A1A1F 0%, #6B1F2F 100%)',
    welcome: 'You are seated.',
    promise: 'Three visits — an amuse-bouche from the chef on your next.',
    coupon: 'ATL-14-K7',
    voice: 'considered, quiet',
    activity: { title: 'Write a thoughtful review (100+ words)', reward: 'seasonal menu preview' },
  },
};

window.BRANDS = BRANDS;
